export const symbols = [
  'BINANCE:ETHUSDT',
  'BINANCE:BTCUSDT',
  'BINANCE:JTOUSDT',
  'BINANCE:AUCTIONUSDT',
  'BINANCE:GXSUSDT',
  'BINANCE:ASRUSDT',
  'BINANCE:BELUSDT',
  'BINANCE:USDTBRL',
  'BINANCE:ACHUSDT',
]
